[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
cmds = ["cd backend && pip install poetry && poetry install --no-dev"]

[start]
cmd = "cd backend && poetry run uvicorn app.main:app --host 0.0.0.0 --port $PORT"
