[phases.setup]
nixPkgs = ["python310", "postgresql"]

[phases.install]
cmds = [
  "cd backend",
  "pip install poetry",
  "poetry config virtualenvs.create false",
  "poetry install --no-dev --no-interaction --no-ansi"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
